from __future__ import annotations

import argparse
import json
import os
import random
import time
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path("/home/wjq/cmllm")
OUT_ROOT = ROOT / "outputs/mr_data/helmet_miner_pseudopair_v1"


PAIR_SYSTEM = """You are a strict data quality auditor for a coal mine multi-round segmentation dataset.

You receive structured metadata for a pseudo coal miner and a mining helmet pair.
The miner is pseudo-labeled by a detector and SAM.
The helmet bbox is a real dataset annotation, and the helmet mask is generated by SAM from the real bbox.

Judge whether this pair is logically suitable for:
Round 1: segment pseudo miner.
Round 2: use the pseudo miner as [REF] and segment the helmet on his head.

Do not assume visual facts that are not supported by the metadata.
Return valid JSON only."""


EPISODE_SYSTEM = """You are auditing a multi-round LISA++ training episode.

Check whether the episode is logically valid:
Round 1 should segment a pseudo coal miner.
Round 2 should use that miner as [REF] and segment the corresponding mining helmet.

The Round 2 query must require the [REF]. It should not be answerable as a single-round "segment the helmet" query.
The metadata must clearly mark pseudo miner masks as pseudo and helmet masks as SAM masks generated from real bboxes.

Return valid JSON only."""


SUMMARY_SYSTEM = """You are reviewing a generated data quality report for a coal mine multi-round segmentation dataset.

Summarize whether the data is ready for the next model-design step.
Focus on failure modes, threshold risks, QC distributions, and whether the reported counts meet the stated acceptance targets.
Return concise Markdown."""


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def append_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def load_key(args: argparse.Namespace) -> tuple[str | None, str]:
    if args.no_api:
        return None, "disabled_by_no_api"
    if args.api_key_file:
        key_path = Path(args.api_key_file)
    elif os.environ.get("DEEPSEEK_API_KEY_FILE"):
        key_path = Path(os.environ["DEEPSEEK_API_KEY_FILE"])
    else:
        key_path = None
    if key_path and key_path.exists():
        key = key_path.read_text(encoding="utf-8").strip()
        if args.consume_api_key_file:
            try:
                key_path.unlink()
            except OSError:
                pass
        return key or None, f"file:{key_path}"
    key = os.environ.get("DEEPSEEK_API_KEY")
    return (key.strip() if key else None), "env:DEEPSEEK_API_KEY" if key else "missing"


def strip_code_fence(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return text


def parse_json_response(text: str) -> dict[str, Any]:
    raw = strip_code_fence(text)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        start = raw.find("{")
        end = raw.rfind("}")
        if start < 0 or end <= start:
            raise
        payload = json.loads(raw[start : end + 1])
    if not isinstance(payload, dict):
        raise ValueError("DeepSeek response is not a JSON object")
    return payload


def call_deepseek(
    *,
    api_key: str,
    base_url: str,
    model: str,
    messages: list[dict[str, str]],
    timeout: int,
    retries: int,
    json_output: bool = True,
) -> dict[str, Any] | str:
    url = base_url.rstrip("/") + "/chat/completions"
    body: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "temperature": 0.0,
    }
    if json_output:
        body["response_format"] = {"type": "json_object"}
    data = json.dumps(body, ensure_ascii=False).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }
    last_error: Exception | None = None
    for attempt in range(retries + 1):
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                payload = json.loads(resp.read().decode("utf-8"))
            content = payload["choices"][0]["message"]["content"]
            return parse_json_response(content) if json_output else content
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, KeyError, json.JSONDecodeError, ValueError) as exc:
            last_error = exc
            if attempt >= retries:
                break
            time.sleep(min(20, 2 ** attempt))
    raise RuntimeError(f"DeepSeek call failed: {last_error}")


def compact_pair(pair: dict[str, Any]) -> dict[str, Any]:
    return {
        "pair_id": pair["pair_id"],
        "rule_decision": pair.get("rule_decision"),
        "selected_for_episode": pair.get("selected_for_episode"),
        "helmet": {
            "id": pair.get("helmet_id"),
            "bbox_xyxy": pair.get("helmet_bbox_xyxy"),
            "target_bbox_source": pair.get("helmet_target_bbox_source"),
            "target_mask_source": pair.get("helmet_target_mask_source"),
        },
        "pseudo_miner": {
            "id": pair.get("pseudo_miner_id"),
            "bbox_xyxy": pair.get("miner_bbox_xyxy"),
            "det_conf": pair.get("det_conf"),
            "sam_quality": pair.get("sam_quality"),
            "annotation_source": pair.get("miner_annotation_source"),
        },
        "geometry": {
            "helmet_center_in_miner": pair.get("helmet_center_in_miner"),
            "helmet_center_in_expanded_miner": pair.get("helmet_center_in_expanded_miner"),
            "helmet_center_in_head_strict": pair.get("helmet_center_in_head_strict"),
            "helmet_center_in_head_loose": pair.get("helmet_center_in_head_loose"),
            "center_in_head_score": pair.get("center_in_head_score"),
            "helmet_head_overlap": pair.get("helmet_head_overlap"),
            "containment": pair.get("containment"),
            "size_score": pair.get("size_score"),
            "helmet_area_over_miner_area": pair.get("helmet_area_over_miner_area"),
            "top1_minus_top2": pair.get("top1_minus_top2"),
            "ambiguous_score_gap": pair.get("ambiguous_score_gap"),
            "ambiguous_multi_head_match": pair.get("ambiguous_multi_head_match"),
        },
        "pair_score": pair.get("pair_score"),
    }


def compact_episode(ep: dict[str, Any]) -> dict[str, Any]:
    r1, r2 = ep["rounds"]
    return {
        "episode_id": ep["episode_id"],
        "episode_type": ep.get("episode_type"),
        "pair_score": ep.get("pair_score"),
        "pair_confidence": ep.get("pair_confidence"),
        "round1": {
            "query": r1.get("query"),
            "target_category": r1.get("target_category"),
            "target_type": r1.get("target_type"),
            "annotation_source": r1.get("annotation_source"),
            "loss_weight": r1.get("loss_weight"),
        },
        "round2": {
            "query": r2.get("query"),
            "ref_category": r2.get("refs_bank", [{}])[0].get("category"),
            "target_category": r2.get("target_category"),
            "target_type": r2.get("target_type"),
            "annotation_source": r2.get("annotation_source"),
            "loss_weight": r2.get("loss_weight"),
        },
    }


def fallback_pair_qc(pair: dict[str, Any], reason: str) -> dict[str, Any]:
    decision = "review"
    risk = "medium"
    failures: list[str] = []
    if pair.get("ambiguous_score_gap"):
        failures.append("ambiguous_pair_score_gap")
    if pair.get("ambiguous_multi_head_match"):
        failures.append("ambiguous_multi_head_match")
    if not pair.get("helmet_center_in_miner"):
        failures.append("helmet_center_not_in_miner_bbox")
    if pair.get("center_in_head_score", 0.0) < 0.7:
        failures.append("weak_head_region_relation")
    if pair.get("sam_quality", 0.0) < 0.45:
        failures.append("low_miner_mask_quality")
    if pair.get("rule_decision") == "high" and not failures:
        decision = "accept"
        risk = "low"
    elif pair.get("rule_decision") == "low" or len(failures) >= 2:
        decision = "reject"
        risk = "high"
    recommended = {
        "accept": "main_train" if pair.get("rule_decision") == "high" else "weak_train",
        "review": "val_review",
        "reject": "reject",
    }[decision]
    return {
        "pair_id": pair["pair_id"],
        "used_api_key": False,
        "model": "fallback_rules",
        "decision": decision,
        "risk_level": risk,
        "main_reason": reason,
        "failure_modes": failures,
        "recommended_use": recommended,
        "rule_decision": pair.get("rule_decision"),
        "pair_score": pair.get("pair_score"),
    }


def fallback_episode_qc(ep: dict[str, Any], reason: str) -> dict[str, Any]:
    r1, r2 = ep["rounds"]
    q2 = str(r2.get("query", "")).lower()
    requires_ref = any(token in q2 for token in ["previous", "prior", "reference", "refer", "selected"])
    valid = (
        r1.get("target_category") == "coal_miner"
        and r1.get("target_type") == "pseudo"
        and r2.get("target_category") == "mining_helmet"
        and r2.get("target_type") == "sam_mask_from_real_bbox"
        and requires_ref
    )
    return {
        "episode_id": ep["episode_id"],
        "used_api_key": False,
        "model": "fallback_rules",
        "valid_episode": bool(valid),
        "round2_requires_ref": bool(requires_ref),
        "has_target_leakage": False,
        "pseudo_real_labeling_clear": bool(r1.get("target_type") == "pseudo" and "sam" in str(r2.get("target_type"))),
        "query_quality": "good" if requires_ref else "weak",
        "decision": "keep" if valid else "review",
        "main_reason": reason,
    }


def normalize_pair_qc(pair: dict[str, Any], raw: dict[str, Any], used_api: bool, model: str) -> dict[str, Any]:
    decision = str(raw.get("decision", "review")).lower()
    if decision not in {"accept", "review", "reject"}:
        decision = "review"
    risk = str(raw.get("risk_level", "medium")).lower()
    if risk not in {"low", "medium", "high"}:
        risk = "medium"
    recommended = str(raw.get("recommended_use", "val_review"))
    if recommended not in {"main_train", "weak_train", "val_review", "reject"}:
        recommended = "val_review"
    failures = raw.get("failure_modes", [])
    if not isinstance(failures, list):
        failures = [str(failures)]
    return {
        "pair_id": pair["pair_id"],
        "used_api_key": used_api,
        "model": model,
        "decision": decision,
        "risk_level": risk,
        "main_reason": str(raw.get("main_reason", ""))[:600],
        "failure_modes": [str(x)[:120] for x in failures],
        "recommended_use": recommended,
        "rule_decision": pair.get("rule_decision"),
        "pair_score": pair.get("pair_score"),
    }


def normalize_episode_qc(ep: dict[str, Any], raw: dict[str, Any], used_api: bool, model: str) -> dict[str, Any]:
    decision = str(raw.get("decision", "review")).lower()
    if decision not in {"keep", "review", "reject"}:
        decision = "review"
    return {
        "episode_id": ep["episode_id"],
        "used_api_key": used_api,
        "model": model,
        "valid_episode": bool(raw.get("valid_episode", False)),
        "round2_requires_ref": bool(raw.get("round2_requires_ref", False)),
        "has_target_leakage": bool(raw.get("has_target_leakage", False)),
        "pseudo_real_labeling_clear": bool(raw.get("pseudo_real_labeling_clear", False)),
        "query_quality": str(raw.get("query_quality", "unknown"))[:80],
        "decision": decision,
        "main_reason": str(raw.get("main_reason", ""))[:600],
        "pair_score": ep.get("pair_score"),
    }


def select_pairs_for_qc(pairs: list[dict[str, Any]], low_sample: int, seed: int) -> list[dict[str, Any]]:
    high_medium = [p for p in pairs if p.get("rule_decision") in {"high", "medium"}]
    low = [p for p in pairs if p.get("rule_decision") == "low"]
    rng = random.Random(seed)
    rng.shuffle(low)
    return high_medium + low[:low_sample]


def chunks(items: list[Any], size: int) -> list[list[Any]]:
    return [items[i : i + size] for i in range(0, len(items), size)]


def run_pair_qc(args: argparse.Namespace, api_key: str | None, key_source: str) -> list[dict[str, Any]]:
    pair_path = args.out_dir / "helmet_miner_pairs.jsonl"
    out_path = args.out_dir / "reports/deepseek_qc_pairs.jsonl"
    pairs = select_pairs_for_qc(read_jsonl(pair_path), args.low_sample, args.seed)
    if args.max_pairs:
        pairs = pairs[: args.max_pairs]
    existing = {row["pair_id"]: row for row in read_jsonl(out_path)}
    todo = [pair for pair in pairs if args.force or pair["pair_id"] not in existing]
    done = len(existing)
    if not todo:
        return read_jsonl(out_path)
    if not api_key:
        for batch in chunks(todo, args.batch_size):
            rows = [fallback_pair_qc(pair, f"DeepSeek API unavailable ({key_source}); fallback rule QC used.") for pair in batch]
            append_jsonl(out_path, rows)
            done += len(rows)
            print(f"pair_qc done={done}/{len(pairs)}", flush=True)
        return read_jsonl(out_path)

    for batch in chunks(todo, args.batch_size):
        user = json.dumps(
            {
                "instruction": (
                    "Audit each item independently. Return a JSON object with key 'items'. "
                    "Each item must include pair_id, decision, risk_level, main_reason, "
                    "failure_modes, and recommended_use."
                ),
                "items": [compact_pair(pair) for pair in batch],
                "allowed_values": {
                    "decision": ["accept", "review", "reject"],
                    "risk_level": ["low", "medium", "high"],
                    "recommended_use": ["main_train", "weak_train", "val_review", "reject"],
                },
            },
            ensure_ascii=False,
        )
        try:
            raw = call_deepseek(
                api_key=api_key,
                base_url=args.base_url,
                model=args.pair_model,
                messages=[{"role": "system", "content": PAIR_SYSTEM}, {"role": "user", "content": user}],
                timeout=args.timeout,
                retries=args.retries,
                json_output=True,
            )
            assert isinstance(raw, dict)
            raw_items = raw.get("items")
            if not isinstance(raw_items, list):
                raise ValueError("pair batch response missing items list")
            by_id = {str(item.get("pair_id")): item for item in raw_items if isinstance(item, dict)}
            missing_ids = [pair["pair_id"] for pair in batch if pair["pair_id"] not in by_id]
            if missing_ids and args.strict_api_qc:
                missing_pairs = [pair for pair in batch if pair["pair_id"] not in by_id]
                for retry_batch in chunks(missing_pairs, max(1, args.strict_retry_batch_size)):
                    retry_user = json.dumps(
                        {
                            "instruction": (
                                "Audit each item independently. Return a JSON object with key 'items'. "
                                "Each item must include pair_id, decision, risk_level, main_reason, "
                                "failure_modes, and recommended_use."
                            ),
                            "items": [compact_pair(pair) for pair in retry_batch],
                            "allowed_values": {
                                "decision": ["accept", "review", "reject"],
                                "risk_level": ["low", "medium", "high"],
                                "recommended_use": ["main_train", "weak_train", "val_review", "reject"],
                            },
                        },
                        ensure_ascii=False,
                    )
                    retry_raw = call_deepseek(
                        api_key=api_key,
                        base_url=args.base_url,
                        model=args.pair_model,
                        messages=[{"role": "system", "content": PAIR_SYSTEM}, {"role": "user", "content": retry_user}],
                        timeout=args.timeout,
                        retries=args.retries,
                        json_output=True,
                    )
                    assert isinstance(retry_raw, dict)
                    retry_items = retry_raw.get("items")
                    if not isinstance(retry_items, list):
                        raise ValueError("pair retry response missing items list")
                    by_id.update({str(item.get("pair_id")): item for item in retry_items if isinstance(item, dict)})
                missing_ids = [pair["pair_id"] for pair in batch if pair["pair_id"] not in by_id]
                for _attempt in range(args.strict_single_id_retries):
                    if not missing_ids:
                        break
                    for pair in [pair for pair in batch if pair["pair_id"] in set(missing_ids)]:
                        single_user = json.dumps(
                            {
                                "instruction": (
                                    "Audit this single item. Return a JSON object with key 'items' containing exactly one item. "
                                    "The item must include pair_id, decision, risk_level, main_reason, failure_modes, and recommended_use."
                                ),
                                "items": [compact_pair(pair)],
                                "allowed_values": {
                                    "decision": ["accept", "review", "reject"],
                                    "risk_level": ["low", "medium", "high"],
                                    "recommended_use": ["main_train", "weak_train", "val_review", "reject"],
                                },
                            },
                            ensure_ascii=False,
                        )
                        single_raw = call_deepseek(
                            api_key=api_key,
                            base_url=args.base_url,
                            model=args.pair_model,
                            messages=[{"role": "system", "content": PAIR_SYSTEM}, {"role": "user", "content": single_user}],
                            timeout=args.timeout,
                            retries=args.retries,
                            json_output=True,
                        )
                        assert isinstance(single_raw, dict)
                        single_items = single_raw.get("items")
                        if isinstance(single_items, list):
                            by_id.update({str(item.get("pair_id")): item for item in single_items if isinstance(item, dict)})
                    missing_ids = [pair["pair_id"] for pair in batch if pair["pair_id"] not in by_id]
                if missing_ids:
                    raise ValueError(
                        f"pair batch response missed {len(missing_ids)} ids after strict retries; first missing ids: {missing_ids[:5]}"
                    )
            rows = [
                normalize_pair_qc(pair, by_id[pair["pair_id"]], True, args.pair_model)
                if pair["pair_id"] in by_id
                else fallback_pair_qc(pair, "DeepSeek batch response missed this pair; fallback rule QC used.")
                for pair in batch
            ]
        except Exception as exc:  # noqa: BLE001
            if args.strict_api_qc:
                raise RuntimeError(f"Strict pair QC failed before writing fallback rows: {exc}") from exc
            rows = [fallback_pair_qc(pair, f"DeepSeek batch error; fallback rule QC used: {str(exc)[:240]}") for pair in batch]
        append_jsonl(out_path, rows)
        done += len(rows)
        print(f"pair_qc done={done}/{len(pairs)}", flush=True)
    return read_jsonl(out_path)


def run_episode_qc(args: argparse.Namespace, api_key: str | None, key_source: str) -> list[dict[str, Any]]:
    ep_path = args.out_dir / "episodes_miner_to_helmet_v1.jsonl"
    out_path = args.out_dir / "reports/deepseek_qc_episodes.jsonl"
    episodes = read_jsonl(ep_path)
    if args.max_episodes:
        episodes = episodes[: args.max_episodes]
    existing = {row["episode_id"]: row for row in read_jsonl(out_path)}
    todo = [ep for ep in episodes if args.force or ep["episode_id"] not in existing]
    done = len(existing)
    if not todo:
        return read_jsonl(out_path)
    if not api_key:
        for batch in chunks(todo, args.batch_size):
            rows = [fallback_episode_qc(ep, f"DeepSeek API unavailable ({key_source}); fallback rule QC used.") for ep in batch]
            append_jsonl(out_path, rows)
            done += len(rows)
            print(f"episode_qc done={done}/{len(episodes)}", flush=True)
        return read_jsonl(out_path)

    for batch in chunks(todo, args.batch_size):
        user = json.dumps(
            {
                "instruction": (
                    "Audit each episode independently. Return a JSON object with key 'items'. "
                    "Each item must include episode_id, valid_episode, round2_requires_ref, "
                    "has_target_leakage, pseudo_real_labeling_clear, query_quality, decision, "
                    "and main_reason."
                ),
                "items": [compact_episode(ep) for ep in batch],
                "allowed_values": {
                    "decision": ["keep", "review", "reject"],
                    "query_quality": ["good", "weak", "bad"],
                },
            },
            ensure_ascii=False,
        )
        try:
            raw = call_deepseek(
                api_key=api_key,
                base_url=args.base_url,
                model=args.episode_model,
                messages=[{"role": "system", "content": EPISODE_SYSTEM}, {"role": "user", "content": user}],
                timeout=args.timeout,
                retries=args.retries,
                json_output=True,
            )
            assert isinstance(raw, dict)
            raw_items = raw.get("items")
            if not isinstance(raw_items, list):
                raise ValueError("episode batch response missing items list")
            by_id = {str(item.get("episode_id")): item for item in raw_items if isinstance(item, dict)}
            missing_ids = [ep["episode_id"] for ep in batch if ep["episode_id"] not in by_id]
            if missing_ids and args.strict_api_qc:
                missing_episodes = [ep for ep in batch if ep["episode_id"] not in by_id]
                for retry_batch in chunks(missing_episodes, max(1, args.strict_retry_batch_size)):
                    retry_user = json.dumps(
                        {
                            "instruction": (
                                "Audit each episode independently. Return a JSON object with key 'items'. "
                                "Each item must include episode_id, valid_episode, round2_requires_ref, "
                                "has_target_leakage, pseudo_real_labeling_clear, query_quality, decision, "
                                "and main_reason."
                            ),
                            "items": [compact_episode(ep) for ep in retry_batch],
                            "allowed_values": {
                                "decision": ["keep", "review", "reject"],
                                "query_quality": ["good", "weak", "bad"],
                            },
                        },
                        ensure_ascii=False,
                    )
                    retry_raw = call_deepseek(
                        api_key=api_key,
                        base_url=args.base_url,
                        model=args.episode_model,
                        messages=[{"role": "system", "content": EPISODE_SYSTEM}, {"role": "user", "content": retry_user}],
                        timeout=args.timeout,
                        retries=args.retries,
                        json_output=True,
                    )
                    assert isinstance(retry_raw, dict)
                    retry_items = retry_raw.get("items")
                    if not isinstance(retry_items, list):
                        raise ValueError("episode retry response missing items list")
                    by_id.update({str(item.get("episode_id")): item for item in retry_items if isinstance(item, dict)})
                missing_ids = [ep["episode_id"] for ep in batch if ep["episode_id"] not in by_id]
                for _attempt in range(args.strict_single_id_retries):
                    if not missing_ids:
                        break
                    for ep in [ep for ep in batch if ep["episode_id"] in set(missing_ids)]:
                        single_user = json.dumps(
                            {
                                "instruction": (
                                    "Audit this single episode. Return a JSON object with key 'items' containing exactly one item. "
                                    "The item must include episode_id, valid_episode, round2_requires_ref, has_target_leakage, "
                                    "pseudo_real_labeling_clear, query_quality, decision, and main_reason."
                                ),
                                "items": [compact_episode(ep)],
                                "allowed_values": {
                                    "decision": ["keep", "review", "reject"],
                                    "query_quality": ["good", "weak", "bad"],
                                },
                            },
                            ensure_ascii=False,
                        )
                        single_raw = call_deepseek(
                            api_key=api_key,
                            base_url=args.base_url,
                            model=args.episode_model,
                            messages=[{"role": "system", "content": EPISODE_SYSTEM}, {"role": "user", "content": single_user}],
                            timeout=args.timeout,
                            retries=args.retries,
                            json_output=True,
                        )
                        assert isinstance(single_raw, dict)
                        single_items = single_raw.get("items")
                        if isinstance(single_items, list):
                            by_id.update({str(item.get("episode_id")): item for item in single_items if isinstance(item, dict)})
                    missing_ids = [ep["episode_id"] for ep in batch if ep["episode_id"] not in by_id]
                if missing_ids:
                    raise ValueError(
                        f"episode batch response missed {len(missing_ids)} ids after strict retries; first missing ids: {missing_ids[:5]}"
                    )
            rows = [
                normalize_episode_qc(ep, by_id[ep["episode_id"]], True, args.episode_model)
                if ep["episode_id"] in by_id
                else fallback_episode_qc(ep, "DeepSeek batch response missed this episode; fallback rule QC used.")
                for ep in batch
            ]
        except Exception as exc:  # noqa: BLE001
            if args.strict_api_qc:
                raise RuntimeError(f"Strict episode QC failed before writing fallback rows: {exc}") from exc
            rows = [fallback_episode_qc(ep, f"DeepSeek batch error; fallback rule QC used: {str(exc)[:240]}") for ep in batch]
        append_jsonl(out_path, rows)
        done += len(rows)
        print(f"episode_qc done={done}/{len(episodes)}", flush=True)
    return read_jsonl(out_path)


def pct(n: int, d: int) -> float:
    return float(n / d) if d else 0.0


def build_summary_payload(out_dir: Path, pair_qc: list[dict[str, Any]], episode_qc: list[dict[str, Any]]) -> dict[str, Any]:
    stats_path = out_dir / "reports/episode_stats.json"
    stats = json.loads(stats_path.read_text(encoding="utf-8")) if stats_path.exists() else {}
    pair_decisions = Counter(row.get("decision") for row in pair_qc)
    pair_risks = Counter(row.get("risk_level") for row in pair_qc)
    pair_by_rule: dict[str, Counter[str]] = {}
    for row in pair_qc:
        pair_by_rule.setdefault(str(row.get("rule_decision")), Counter())[str(row.get("decision"))] += 1
    ep_decisions = Counter(row.get("decision") for row in episode_qc)
    ep_valid = sum(1 for row in episode_qc if row.get("valid_episode"))
    ep_requires_ref = sum(1 for row in episode_qc if row.get("round2_requires_ref"))
    high_qc = [row for row in pair_qc if row.get("rule_decision") == "high"]
    high_accept = sum(1 for row in high_qc if row.get("decision") == "accept")
    high_reject = sum(1 for row in high_qc if row.get("decision") == "reject")
    return {
        "dataset_stats": stats,
        "deepseek_qc": {
            "pair_total_reviewed": len(pair_qc),
            "pair_decisions": dict(pair_decisions),
            "pair_risks": dict(pair_risks),
            "pair_decisions_by_rule": {k: dict(v) for k, v in pair_by_rule.items()},
            "high_pair_accept_rate": pct(high_accept, len(high_qc)),
            "high_pair_reject_rate": pct(high_reject, len(high_qc)),
            "episode_total_reviewed": len(episode_qc),
            "episode_decisions": dict(ep_decisions),
            "episode_valid_rate": pct(ep_valid, len(episode_qc)),
            "episode_round2_requires_ref_rate": pct(ep_requires_ref, len(episode_qc)),
        },
        "acceptance_targets": {
            "high_confidence_pair_min": 3000,
            "high_pair_accept_rate_min": 0.90,
            "high_pair_reject_rate_max": 0.05,
            "episode_valid_rate_min": 0.95,
            "episode_round2_requires_ref_rate_min": 0.95,
            "core_counterfactual_min": 300,
            "overlay_subjective_correct_rate_min": 0.85,
        },
    }


def fallback_markdown_summary(payload: dict[str, Any], reason: str) -> str:
    stats = payload.get("dataset_stats", {})
    qc = payload.get("deepseek_qc", {})
    lines = [
        "# DeepSeek QC Summary",
        "",
        f"DeepSeek API summary model was not used: {reason}",
        "",
        "## Counts",
        f"- Main high pairs for episodes: {stats.get('main_high_pairs_for_episodes', 0)}",
        f"- Episodes: {stats.get('episodes', 0)}",
        f"- Core counterfactual episodes: {stats.get('counterfactual_core', 0)}",
        f"- Pair QC reviewed: {qc.get('pair_total_reviewed', 0)}",
        f"- Episode QC reviewed: {qc.get('episode_total_reviewed', 0)}",
        "",
        "## QC Rates",
        f"- High pair accept rate: {qc.get('high_pair_accept_rate', 0.0):.3f}",
        f"- High pair reject rate: {qc.get('high_pair_reject_rate', 0.0):.3f}",
        f"- Episode valid rate: {qc.get('episode_valid_rate', 0.0):.3f}",
        f"- Episode round2 requires ref rate: {qc.get('episode_round2_requires_ref_rate', 0.0):.3f}",
        "",
        "## Notes",
        "- This summary may include fallback rule QC if no DeepSeek key was available.",
        "- Visual overlay review is still required before using the dataset as a core MR training set.",
    ]
    return "\n".join(lines) + "\n"


def write_summary(args: argparse.Namespace, api_key: str | None, key_source: str, pair_qc: list[dict[str, Any]], episode_qc: list[dict[str, Any]]) -> None:
    payload = build_summary_payload(args.out_dir, pair_qc, episode_qc)
    write_json(args.out_dir / "reports/deepseek_qc_distribution.json", payload)
    if not api_key:
        text = fallback_markdown_summary(payload, f"API unavailable ({key_source})")
    else:
        try:
            result = call_deepseek(
                api_key=api_key,
                base_url=args.base_url,
                model=args.summary_model,
                messages=[
                    {"role": "system", "content": SUMMARY_SYSTEM},
                    {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
                ],
                timeout=args.timeout,
                retries=args.retries,
                json_output=False,
            )
            assert isinstance(result, str)
            text = result
        except Exception as exc:  # noqa: BLE001
            text = fallback_markdown_summary(payload, f"summary API error: {str(exc)[:240]}")
    (args.out_dir / "reports/deepseek_qc_summary.md").write_text(text.strip() + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Structured DeepSeek QC for MiningHelmet-with-PseudoMiner v1.")
    parser.add_argument("--out-dir", type=Path, default=OUT_ROOT)
    parser.add_argument("--base-url", default=os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com"))
    parser.add_argument("--pair-model", default=os.environ.get("DEEPSEEK_PAIR_MODEL", "deepseek-v4-flash"))
    parser.add_argument("--episode-model", default=os.environ.get("DEEPSEEK_EPISODE_MODEL", "deepseek-v4-flash"))
    parser.add_argument("--summary-model", default=os.environ.get("DEEPSEEK_SUMMARY_MODEL", "deepseek-v4-pro"))
    parser.add_argument("--api-key-file", default="")
    parser.add_argument("--consume-api-key-file", action="store_true")
    parser.add_argument("--no-api", action="store_true")
    parser.add_argument("--low-sample", type=int, default=500)
    parser.add_argument("--batch-size", type=int, default=40)
    parser.add_argument(
        "--strict-api-qc",
        action="store_true",
        help="When an API key is used, fail on API/batch validation errors instead of writing fallback rows.",
    )
    parser.add_argument(
        "--strict-retry-batch-size",
        type=int,
        default=10,
        help="In strict API QC, retry missing ids from a larger batch with this smaller batch size before failing.",
    )
    parser.add_argument(
        "--strict-single-id-retries",
        type=int,
        default=3,
        help="In strict API QC, retry any still-missing ids one item at a time before failing.",
    )
    parser.add_argument("--max-pairs", type=int, default=0)
    parser.add_argument("--max-episodes", type=int, default=0)
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--seed", type=int, default=20260510)
    parser.add_argument("--force", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    (args.out_dir / "reports").mkdir(parents=True, exist_ok=True)
    api_key, key_source = load_key(args)
    pair_qc = run_pair_qc(args, api_key, key_source)
    episode_qc = run_episode_qc(args, api_key, key_source)
    write_summary(args, api_key, key_source, pair_qc, episode_qc)
    print(json.dumps(build_summary_payload(args.out_dir, pair_qc, episode_qc), ensure_ascii=False, indent=2), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
